create table transaction_entity
(
    amount                  bigint                      not null,
    date                    timestamp(6) with time zone not null,
    id                      bigint generated by default as identity,
    account_number          varchar(255)                not null,
    description             varchar(255),
    tracking_number         varchar(255)                not null,
    transfer_account_number varchar(255),
    transaction_type        enum ('DEPOSIT','WITHDRAW') not null,
    primary key (id)
);
create table user_account
(
    is_active      boolean,
    id             bigint generated by default as identity,
    account_number varchar(255) not null unique,
    firstname      varchar(255),
    lastname       varchar(255),
    password       varchar(255) not null,
    roles          varchar(255),
    username       varchar(255) not null unique,
    primary key (id)
);
